### PR TITLE
ci: Packit: Run cockpit storage tests in PRs

### PR DESCRIPTION
**Pull request by martinpitt**
See https://cockpit-project.org/blog/tmt-cross-project-testing.html

 - [x] Depends on https://github.com/storaged-project/udisks/pull/1159
 - [x] Depends on https://github.com/cockpit-project/cockpit/pull/19168

### CODE REVIEW

**Comment by martinpitt** [comment]
@thrix, @happz: The -revdeps test for Fedora 38 [fails to install](https://artifacts.dev.testing-farm.io/15a73f7f-1b28-41a6-9de0-6b09d75c3758/#artifacts-/plans/cockpit/optional) because it doesn't see the libblockdev* packages from the [@storage/udisks-daily COPR](https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily). I did add that to the [.packit.yaml](https://github.com/martinpitt/udisks/commit/4aa505fc617a8b7ce6bae7c71f5cd2d9a43c49a9#diff-2b4300f6d69654fd71c0cdd329b5a5f13fa8fe7eb709c76276bdfd3ea1dde578R39) here:
```yaml
- type: repository-file
  id: https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/repo/fedora-$releasever/group_storage-udisks-daily-fedora-$releasever.repo
```
in exactly the same way that I add the cockpit "main-builds" COPR.

This is plumbed through via `tf_extra_params:`, and I do see it in the `REQUEST`; reformatted JSON for convenience:

```json
{
    "id": "15a73f7f-1b28-41a6-9de0-6b09d75c3758",
    "environments_requested": [
        {
           "artifacts": [
                {
                    "id": "https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/repo/fedora-$releasever/group_cockpit-main-builds-fedora-$releasever.repo",
                    "packages": null,
                    "type": "repository-file"
                },
                {
                    "id": "https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/repo/fedora-$releasever/group_storage-udisks-daily-fedora-$releasever.repo",
                    "packages": null,
                    "type": "repository-file"
                }
            ]
     [...]
}
```

Do you know what's wrong here? Thanks!

**Comment by martinpitt** [comment]
Rawhide [got a little further](https://artifacts.dev.testing-farm.io/e99bb448-e641-479c-be99-28a3c1a4841e/) , but only because the [install-packages step](https://artifacts.dev.testing-farm.io/e99bb448-e641-479c-be99-28a3c1a4841e/guest-setup-eab057bb-1fa0-4476-b495-4e91d92a81e3/artifact-installation-eab057bb-1fa0-4476-b495-4e91d92a81e3/4-Install-packages.txt) grabs libblockdev* from rawhide instead of the udisks-daily COPR.

**Comment by thrix** [comment]
the deployment was outdated, now it should work as designed

**Comment by martinpitt** [comment]
Amazing, it works perfectly. Many thanks @thrix!

I close this now and open a PR against the real udisks project.

**Comment by martinpitt** [comment]
See https://github.com/storaged-project/udisks/pull/1161

**Pull request closed without merging**
